alter table VAC_VACATION add constraint FK_VAC_VACATION_ON_APPLICATION foreign key (APPLICATION_ID) references SYS_FILE(ID);
create index IDX_VAC_VACATION_ON_APPLICATION on VAC_VACATION (APPLICATION_ID);
